---
- hosts: all
  become: yes
  tasks:
    - name: Install pip3
      apt:
        name: python3-pip
        update_cache: yes
        state: present
    - name: Upgrade pip3
      pip:
        name: pip
        executable: pip3
        state: latest
    - name: Install docker-py
      pip:
        name: 
          - docker
          - docker-compose
        executable: pip3
        state: latest
    - name: Create and start services
      community.docker.docker_compose:
        project_src: .
      vars:
        ansible_python_interpreter: /bin/python3
      register: output
