---
- hosts: all
  become: yes
  tasks:
    - name: install docker-compose
      # pip:
      #   name: docker-compose
      #   state: present
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'a+x'
